name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          if [ -z "$COMMIT_MESSAGE" ]; then
            COMMIT_MESSAGE="No commit message provided."
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"username\": \"GitHub Bot\", \
               \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\", \
               \"content\": \"**New Commit on Main Branch**\n**Message:** $COMMIT_MESSAGE\n**Author:** PRG\"}" \
          $DISCORD_WEBHOOK
